### ISSUE TITLE
examples/vaults.py: ImportError: libstdc++.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by dckc** [rchain/pyrchain#12]
I'm struggling to run the vaults example:

```
connolly@jambox:~/projects/pyrchain$ pipenv run python examples/vaults.py
Traceback (most recent call last):
  File "examples/vaults.py", line 3, in <module>
    import grpc
  File "/home/connolly/.local/share/virtualenvs/pyrchain-EG6rQR_o/lib/python3.7/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

I tried to follow the instructions to the letter. Full transcript:
https://gist.github.com/dckc/745686c7387d1a119819f5e250541dbc

I see similar symptoms reported elsewhere, but I don't see an applicable solution.
https://github.com/habitat-sh/core-plans/issues/655

**Comment by zsluedem** [comment]
https://stackoverflow.com/questions/7880454/python-executable-not-finding-libpython-shared-library

How did you install your Python?

**Comment by dckc** [comment]
umm... with nix, evidently:

```
connolly@jambox:~/projects/pyrchain$ pipenv run which python
/home/connolly/.local/share/virtualenvs/pyrchain-EG6rQR_o/bin/python
connolly@jambox:~/projects/pyrchain$ ldd /home/connolly/.local/share/virtualenvs/pyrchain-EG6rQR_o/bin/python
	linux-vdso.so.1 (0x00007fff713fd000)
	libpython3.7m.so.1.0 => /nix/store/0f331h72l3v42szvcqyc9pqg79ghid9m-python3-3.7.3/lib/libpython3.7m.so.1.0 (0x00007f26dabac000)
	libpthread.so.0 => /nix/store/avr2x43njlq4kyb1a9zgrh6fih5fq4si-glibc-2.27/lib/libpthread.so.0 (0x00007f26db118000)
	libdl.so.2 => /nix/store/avr2x43njlq4kyb1a9zgrh6fih5fq4si-glibc-2.27/lib/libdl.so.2 (0x00007f26db113000)
	libcrypt.so.1 => /nix/store/avr2x43njlq4kyb1a9zgrh6fih5fq4si-glibc-2.27/lib/libcrypt.so.1 (0x00007f26db0d9000)
	libncursesw.so.6 => /nix/store/gvfq0jwgdcv0gd6gnm2mbcc97y8scc9v-ncurses-6.1-20190112/lib/libncursesw.so.6 (0x00007f26db067000)
	libutil.so.1 => /nix/store/avr2x43njlq4kyb1a9zgrh6fih5fq4si-glibc-2.27/lib/libutil.so.1 (0x00007f26db060000)
	libm.so.6 => /nix/store/avr2x43njlq4kyb1a9zgrh6fih5fq4si-glibc-2.27/lib/libm.so.6 (0x00007f26daa16000)
	libgcc_s.so.1 => /nix/store/avr2x43njlq4kyb1a9zgrh6fih5fq4si-glibc-2.27/lib/libgcc_s.so.1 (0x00007f26da800000)
	libc.so.6 => /nix/store/avr2x43njlq4kyb1a9zgrh6fih5fq4si-glibc-2.27/lib/libc.so.6 (0x00007f26da64a000)
	/nix/store/avr2x43njlq4kyb1a9zgrh6fih5fq4si-glibc-2.27/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007f26daf14000)
```

stock Ubuntu python 3 is no good either:

```
~/projects/pyrchain$ pipenv run python examples/vaults.py
Warning: Your Pipfile requires python_version 3.7, but you are using 3.6.8 (/home/c/.local/share/v/p/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Traceback (most recent call last):
  File "examples/vaults.py", line 6, in <module>
    from rchain.client import RClient
  File "/home/connolly/projects/pyrchain/rchain/client.py", line 7, in <module>
    from .util import create_deploy_data
  File "/home/connolly/projects/pyrchain/rchain/util.py", line 3, in <module>
    import importlib.resources
ModuleNotFoundError: No module named 'importlib.resources'
```

**Comment by dckc** [comment]
hmm... https://nixos.wiki/wiki/Packaging/Quirks_and_Caveats recommends using LD_LIBRARY_PATH.

Life on the bleeding edge...

**Comment by dckc** [comment]
back to nix, this seems to work:

```
$ LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu pipenv run python examples/vaults.py
...
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
```

which is expected, since I took my node down.

**Comment by artslob** [comment]
This helped me:
```
LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [pkgs.stdenv.cc.cc.lib];
```

**Comment by AgeOfMarcus** [comment]
> This helped me:
> 
> ```
> LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [pkgs.stdenv.cc.cc.lib];
> ```

@artslob where do you put this?

**Comment by artslob** [comment]
@AgeOfMarcus it should work if you put it as is in top level declaration in `pkgs.mkShell` of nix-shell:
```nix
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/....tar.gz") { } }:

pkgs.mkShell {
  buildInputs = with pkgs; [ ... ];

  LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [pkgs.stdenv.cc.cc.lib];
}
```
