### ISSUE TITLE
Error handling fails on propose.

### ISSUE THREAD

**Issue by nzpr** [rchain/pyrchain#24]
When there are no new deploys and gRPC returns

`error {
  messages: "Error while creating block: NoNewDeploys"
}`

error handling fails with

```Traceback (most recent call last):
  File "/opt/rchain-testnet-node/scripts/propose.py", line 6, in <module>
    client.propose()
  File "/opt/rchain-testnet-node/scripts/venv/lib/python3.6/site-packages/rchain/client.py", line 68, in propose
    self._check_response(response)
  File "/opt/rchain-testnet-node/scripts/venv/lib/python3.6/site-packages/rchain/client.py", line 46, in _check_response
    raise RClientException('\n'.join(response.error))
TypeError: can only join an iterable```

**Comment by zsluedem** [comment]
https://github.com/rchain/pyrchain/commit/092c9c4cefd042184ec330854428740e8dca3eca should fix it. 
Feel free to reopen it if you have problems.
